### ISSUE TITLE
colab to reproduce fig2

### ISSUE THREAD

**Issue by JunMa11** [ChenWu98/cycle-diffusion#1]
Hi @ChenWu98 ,

Thanks for sharing the awesome work.

Would it be possible to share a jupyter-notebook to reproduce the results in fig2?

**Comment by ChenWu98** [comment]
For sure! I will update our experimental code (based on CompVis's Stable Diffusion implementation) soon, which can be reproduced. Then I will transfer the implementation to the diffuser library and make a Colab notebook for easier use.

Feel free to leave this issue open until I finish everything!

**Comment by ChenWu98** [comment]
Ohh I just realized you are referring to Fig2 (the unpaired translation instead of the zero-shot translation). The unpaired translation will be open-sourced in this repo with detailed instructions, but probably not as a jupyter-notebook. Thanks!

**Comment by JunMa11** [comment]
Thank you:)
