### ISSUE TITLE
whether the early stop should be applied in unpaired I2I ?

### ISSUE THREAD

**Issue by fortunechen** [ChenWu98/cycle-diffusion#10]
Hi, Chen
I noticed that the early stop should not be used according C.2 in the supplementary. 
<img width="931" alt="image" src="https://user-images.githubusercontent.com/26025440/203037853-b0f162b1-07b7-4895-b27b-b6173ed1f193.png">
However, in your implementation, the early stop is set as [850](https://github.com/ChenWu98/cycle-diffusion/blob/54206c060007d464bbe4c1025ad8303f5f501450/config/experiments/translate_afhqcat256_to_afhqdog256_ddim_eta01.cfg#L14)

**Comment by ChenWu98** [comment]
Hi Zhuowei,

Thanks for double-checking! Yes, changing this value to 1000 will recover the setting described here. I have updated this value to 850 since I find it helps produce better results, and I will update the arxiv version to reflect this change soon. Sorry about the confusion!

**Comment by fortunechen** [comment]
Thx for your reply. :)
