### ISSUE TITLE
Could you please explain what "custom step" and "white_box_step" stand for?

### ISSUE THREAD

**Issue by fortunechen** [ChenWu98/cycle-diffusion#11]
Hi Chen, 

Sorry for bothering you again, you set "custom step=99" and "white_box_step=100" for stable diffusion. Could you please explain what are "custom step" and "white_box_step"? It will be very helpful for me to understand the code. 

Thx

**Comment by ChenWu98** [comment]
Hi Zhuowei,

``custom_step`` is the number of denoising steps, and ``white_box_step`` is the number of noises. When all noises are used (i.e., noises $=$ $\boldsymbol{x}_T, \boldsymbol{\epsilon}_T, \ldots, \boldsymbol{\epsilon}_1$), then ``white_box_step`` $=$ ``custom_step`` + 1. If you want to skip some later noises (e.g., noises $=$ $\boldsymbol{x}_T, \boldsymbol{\epsilon}_T, \ldots, \boldsymbol{\epsilon}_3$), then ``white_box_step`` $\leq$ ``custom_step``; the skipped noises are randomly sampled from the Gaussian when decoding the image. 

By the way, for Stable Diffusion, our implementation based on diffusers ([doc](https://huggingface.co/docs/diffusers/main/en/api/pipelines/cycle_diffusion), [demo](https://huggingface.co/spaces/ChenWu98/Stable-CycleDiffusion)) should be cleaner and easier to play with.

**Comment by fortunechen** [comment]
Thx, I can understand now. Looks great on diffusers. 👍
