### ISSUE TITLE
Unpaired image-to-image translation

### ISSUE THREAD

**Issue by zhangyl660** [ChenWu98/cycle-diffusion#12]
Hi~
I use translate_afhqwild256_to_afhqdog256_ddim_eta01.cfg to excute Unpaired image-to-image translation with diffusion models trained on two domains. I have some problems:
1.I use sample_type = ddim, but I cannot understand what "custom_steps = 1000, refine_steps = 100, es_steps = 850" stand for?
2.Is the denoising steps when training the two models in the source and target domains equal to the customer_steps here?
3.What should I change if I want to use fewer diffusion steps in this code like ddim? I can't find parameters similar to "--timestep_respacing ddim250" in this code.

Thanks a lot!

**Comment by ChenWu98** [comment]
Hi,

a. custom_steps is the fewer diffusion steps used in DDIM.
b. refine_step is the number of SDEdit steps for further refinement of the output (Section 4.1 in the [updated paper](https://arxiv.org/abs/2210.05559)).
c. es_steps is the encoding step described in Algorithm 1 in the [updated paper](https://arxiv.org/abs/2210.05559).

**Comment by zhangyl660** [comment]
Thank you so much!
