### ISSUE TITLE
Please tell train the image to image translation with custom dataset

### ISSUE THREAD

**Issue by chengyu89527** [ChenWu98/cycle-diffusion#15]
I find that the training part code seems incomplete,If we want to train custom data set with your code, what should be done. I also can't find your cycle consistent code, is that not complete yet?  Thanks for sharing your code but please explain better.

Thanks in advance

**Comment by ChenWu98** [comment]
Hi, our method is "zero-shot", meaning that we can use the pretrained weights provided by previous works, and the training codes are provided by the original repositories of the previous works. Please refer to issue #9 for details about how to extend our inference code to custom datasets.
