### ISSUE TITLE
Which part of algorithm 1 stands for cycle, why do you call it cyclediffusion?

### ISSUE THREAD

**Issue by chengyu89527** [ChenWu98/cycle-diffusion#16]
Hi, thanks for your answer, I understand you use the pretrained diffusion model,but I'm still confused why you call alogrithm1 as cycle diffusion. Is it similiar with the idea of cycleGan, I can't find the cycle consistent inside. Do we need extra training to hold the cycle beside the pretrained model?
Thanks again!

**Comment by ChenWu98** [comment]
Hi, the method is based on the observation that cycle consistency *naturally emerges* from diffusion models, i.e., the same random noise leads to similar images. Therefore, there is no training objective that explicitly encourages cycle consistency.

**Comment by chengyu89527** [comment]
Oh, I just view your answer of issue 14, I'm agree with "the same random noise leads to similar images",however I didn't find the cycle consistency description in GLIDE. In my opinion, cycle means translate from domain A to B , and back to A. We need that structure to maintain anatomy stucture in medical images. Is it hard to guarantee the anatomy shape during translation between different domains (T1 to T2)? By the way, the latent code is really big,could we encode it to smaller version ?

**Comment by ChenWu98** [comment]
Yes, I shouldn't say that "cycle consistency naturally emerges from diffusion models", and this is not claimed in our paper. We used the term "cycle-diffusion" simply because it allows unpaired image-to-image translation like CycleGAN. We didn't do experiments on medical images, so I'm not sure whether the shape can be preserved or not (it is possible that the latent codes inferred by DPM-Encoder contain shape information). 

The latent code is indeed big, and I think it is interesting to explore how redundant it is.

**Comment by chengyu89527** [comment]
Thanks for replaying so fast, I understand better. Just a rough idea, It will be helpful if we can separate the latent code into shape and style parts. Will look forward your future work.

**Comment by xiayhh** [comment]
> 哦，我只是查看您对问题 14 的回答，我同意“相同的随机噪声导致相似的图像”，但是我没有在 GLIDE 中找到循环一致性描述。在我看来，循环意味着从域 A 到 B ，然后再转换回 A。我们需要这种结构来维持医学图像中的解剖结构。在不同域（T1 到 T2）之间的翻译过程中是否很难保证解剖形状？顺便说一下，潜伏代码真的很大，我们可以把它编码成更小的版本吗？
Have you verified the effect of this model in the field of medical images? I hope to get your reply, thank you.

**Comment by xiayhh** [comment]
> Oh, I just view your answer of issue 14, I'm agree with "the same random noise leads to similar images",however I didn't find the cycle consistency description in GLIDE. In my opinion, cycle means translate from domain A to B , and back to A. We need that structure to maintain anatomy stucture in medical images. Is it hard to guarantee the anatomy shape during translation between different domains (T1 to T2)? By the way, the latent code is really big,could we encode it to smaller version ?

Have you verified the effect of this model in the field of medical images? I hope to get your reply, thank you.

**Comment by chengyu89527** [comment]
Sorry I didn't do the experiment about it, Also curious about how to design the  experiment. We may train the model from other dataset instead of using pretrained data

**Comment by xiayhh** [comment]
> Sorry I didn't do the experiment about it, Also curious about how to design the experiment. We may train the model from other dataset instead of using pretrained data
Ok, thanks for your reply.

**Comment by xiayhh** [comment]
Ok, thanks for your reply.
