### ISSUE TITLE
Custom dataset load Issue

### ISSUE THREAD

**Issue by woopo666** [ChenWu98/cycle-diffusion#18]
hello. I run Cycle-diffusion on a custom dataset, but there seems to be a problem with specifying the data.
I modified the "/data/translate-text.json" as you said. also, translate_text512.cfg in the "config" folder was also modified.

The code below is the modified "/config/tasks/translate_text512.cfg"

--------------------------------------------------------------------------------
[raw_data]
data_program = ./raw_data/empty.py
data_cache_dir = ./data/dataset/
use_cache = True

[preprocess]
preprocess_program = translate_text512
expansion = 1

[evaluation]
evaluator_program = translate_text

--------------------------------------------------------------------------------

Q1. It looks like I need to modify the data_program variable to suit me, is that correct?

However, the following error occurs due to incorrect modification.
Below is the text of the error that occurred

Q2. Please see the error below and let me know if you have a solution.

--------------------------------------------------------------------------------
Rank 0 Trainer build successfully.
INFO:__main__:*** Evaluate ***
INFO:trainer.trainer:***** Running eval *****
INFO:trainer.trainer:  Num examples = 0
INFO:trainer.trainer:  Batch size = 1
0it [00:00, ?it/s] 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/mnt/hdd0-4tb/home/cyclediffusion/cycle-diffusion-main/main.py", line 153, in <module>
    main()
  File "/mnt/hdd0-4tb/home/cyclediffusion/cycle-diffusion-main/main.py", line 127, in main
    metrics = trainer.evaluate(
  File "/mnt/hdd0-4tb/home/cyclediffusion/cycle-diffusion-main/trainer/trainer.py", line 1047, in evaluate
    metrics, num_samples = eval_loop(
  File "/mnt/hdd0-4tb/home/cyclediffusion/cycle-diffusion-main/trainer/trainer.py", line 867, in evaluation_loop
    images, weighted_loss, losses = all_prediction_outputs
TypeError: cannot unpack non-iterable NoneType object

**Comment by ChenWu98** [comment]
Sorry for the late reply! If new data are appended to the end of [this json file](https://github.com/ChenWu98/cycle-diffusion/blob/main/data/translate-text.json), nothing needs to be changed. However, if you are overwriting that file, you need to modify [this line](https://github.com/ChenWu98/cycle-diffusion/blob/57036b535f9f9f34ec803a5050ebec1e86be1e82/config/experiments/translate_text2img256_stable_diffusion_stochastic_custom.cfg#L17) as [0, NUM_OF_YOUR_SAMPLES]. The first number 0 was set as 128 to skip the original data.
