### ISSUE TITLE
About outputs issue

### ISSUE THREAD

**Issue by zzz11223345** [ChenWu98/cycle-diffusion#22]
Hi, I trained “translate cat-to-dog”  , and generated a folder called “translate_afhqcat256_to_afhqdog256_ddim_eta0142” in the output folder, but after training for a long time, no images were saved in it. When will the images be saved? Another question is what does “self.output_interval” in “trainer.py” control?

**Comment by AlistairMcCutcheon** [comment]
How did you fix this please? @zzz11223345
