### ISSUE TITLE
No outputs: Unpaired image-to-image translation with diffusion models trained on two domains

### ISSUE THREAD

**Issue by AlistairMcCutcheon** [ChenWu98/cycle-diffusion#23]
Duplicate of #22 

When running the above model, the output folder (translate_afhqcat256_to_afhqdog256_ddim_eta0142) is created, and the model starts to train, but no images (or anything else) is being saved inside that folder. I have been training for several hours, for 150+ iterations. Using all the default parameters on the repo's readme.

**Comment by ChenWu98** [comment]
Hi, can you share the exact command(s) you ran? Our method is training-free, so running commands in the readme should only run evaluation.

**Comment by AlistairMcCutcheon** [comment]
I ran the following (the third line is indntical to what is on the readme except I used torchrun instead of python -m torch.distributed.run):

```
export RUN_NAME=translate_afhqcat256_to_afhqdog256_ddim_eta01
export SEED=42
nohup torchrun --nproc_per_node 1 --master_port 1446 main.py --seed $SEED --cfg experiments/$RUN_NAME.cfg --run_name $RUN_NAME$SEED --logging_strategy steps --logging_first_step true --logging_steps 4 --evaluation_strategy steps --eval_steps 50 --metric_for_best_model CLIPEnergy --greater_is_better false --save_strategy steps --save_steps 50 --save_total_limit 1 --load_best_model_at_end --gradient_accumulation_steps 4 --num_train_epochs 0 --adafactor false --learning_rate 1e-3 --do_eval --output_dir output/$RUN_NAME$SEED --overwrite_output_dir --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --eval_accumulation_steps 4 --ddp_find_unused_parameters true --verbose true > $RUN_NAME$SEED.log 2>&1 &
```

I did not run "export CUDA_VISIBLE_DEVICES=1" as I found it flipped torch.cuda.is_available() to false. 

I'm using pip, not conda - these are my dependencies:
[requirements.txt](https://github.com/ChenWu98/cycle-diffusion/files/12264867/requirements.txt)

I'm running an RTX 3090, python 3.10.12.

**Comment by ChenWu98** [comment]
Thanks for the information. [This line](https://github.com/ChenWu98/cycle-diffusion/blob/85efc74403df7d78b45e8101b520efc7852095a9/evaluation/translate_to_dog.py#L57) should save the images. Can you check if this line is being called?

**Comment by AlistairMcCutcheon** [comment]
@ChenWu98 
Nevermind, it does run, the evaluation just takes forever.
