### ISSUE TITLE
ldm_models.zip  Corrupt files，损坏的文件

### ISSUE THREAD

**Issue by xxddccaa** [ChenWu98/cycle-diffusion#24]
An error occurred while decompressing：
解压的时候出现了错误：

(ldm) home/InST-main/cycle-diffusion-main/ckpts$ unzip ldm_models.zip
Archive:  ldm_models.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ldm_models.zip or
        ldm_models.zip.zip, and cannot find ldm_models.zip.ZIP, period.

**Comment by ChenWu98** [comment]
Hi, I can still download and unzip the file. Can you try removing the file and downloading it again? Maybe your download was corrupted.

**Comment by xxddccaa** [comment]
Thank you very much. I'll try downloading it again. Also, just to mention, this sentence cannot be executed either, as it seems the resource doesn't exist: wget https://image-editing-test-12345.s3-us-west-2.amazonaws.com/checkpoints/celeba_hq.ckpt.

十分感谢，我重新下载一次试一试。另外说一句，这句话也是不能执行的，好像资源不存在的：wget https://image-editing-test-12345.s3-us-west-2.amazonaws.com/checkpoints/celeba_hq.ckpt。

**Comment by xxddccaa** [comment]
click the url https://image-editing-test-12345.s3-us-west-2.amazonaws.com/checkpoints/celeba_hq.ckpt , get :

![image](https://github.com/ChenWu98/cycle-diffusion/assets/25652821/f5e8ee94-f100-46a3-ad48-6a05a9d4d280)

**Comment by ChenWu98** [comment]
I copied the link from [SDEdit](https://github.com/ermongroup/SDEdit/blob/66a5e44db6c36d5979c323781675d67117c0fb04/colab_utils/utils.py#L27), and it seems they have banned this file. 
I found another source for the celeba-hq checkpoint [here](https://drive.google.com/file/d/1cSEIFLjOAyiabGnbIa2ZhelOizRQLerM/view?usp=share_link), but unfortunately, I cannot provide any guarantee for its usefulness/safety.

**Comment by xxddccaa** [comment]
you are really kind and patient! thank you!    I will try, and bring some news up again.

**Comment by xxddccaa** [comment]
The compressed package can be extracted normally after re-downloading. PyTorch version installed is 1.13.1, PyTorch 2.0 is not compatible and has some issues. Everything seems to be working fine now. Thank you.

压缩包重新下载后可以正常解压。pytorch版本装的1.13.1，pytorch 2.0不太兼容有些问题。现在一切看起来都正常工作了。谢谢。
