### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by zy1999822** [ChenWu98/cycle-diffusion#27]
[Customized use for zero-shot image-to-image translation] I Follow this step to reproduce
An error occurred as follows:
Traceback (most recent call last):
    File "main.py", line 150, in <module>
        main()
    File "main.py", ine 124, in main
        metrics = trainer.evaluate(
    File "/home/zhangzhang/zz/cycle-diffusion-main/trainer/trainer.py", line 1048, in evaluate
        metrics,num_samples = eval_loop(
    File "/home/zhangzhang/zz/cycle-diffusion-main/trainer/trainer.py", line 867,in evaluation_loop
        images， weighted_loss, losses= all_prediction_outputs
TypeError: cannot unpack non-iterable NoneType object

all_prediction_outputs printed return value is None

Can you tell me how to solve it? Thank you very much!

**Comment by ChenWu98** [comment]
Hi, have you added the data at the end of [this json file](https://github.com/ChenWu98/cycle-diffusion/blob/main/data/translate-text.json)? What our code is doing for this customized use is to skip the first 128 entries in the json file, so make sure that you do not delete the original entries there.

**Comment by ChenWu98** [comment]
Let me know if it does not address the problem!

**Comment by zy1999822** [comment]
Thank you for your answer. Currently, I want to reproduce the effect of your code, so I did not add data at the end of [the json file](https://github.com/ChenWu98/cycle-diffusion/blob/main/data/translate-text.json),  and I did not delete the data that was originally in it. I saw that you said I could add any amount of data as needed, so I didn't add it. Do you mean that I must add my own data to run successfully?

**Comment by ChenWu98** [comment]
To reproduce the results, please follow [this section](https://github.com/ChenWu98/cycle-diffusion#zero-shot-image-to-image-translation-with-text-to-image-diffusion-models) instead of the customized one.

**Comment by zy1999822** [comment]
Thank you for your answer!
