### ISSUE TITLE
Does the unpaired image-to-image translation works with Hugging Face Stable Diffusion checkpoints?

### ISSUE THREAD

**Issue by nityanandmathur** [ChenWu98/cycle-diffusion#29]
Hi! I am trying to run unpaired image-to-image translation on a custom dataset.

I am using Hugging Face [Unconditional Image Generation Pipeline](https://huggingface.co/docs/diffusers/main/en/training/unconditional_training) to train a DDPM model on both domains. 

How can I use the saved checkpoints, which are stored as _safetensors_ for the unpaired I2I translation?

**Comment by ChenWu98** [comment]
Hi! Sorry but I'm not that familiar with safetensors. We trained the model using [this repo](https://github.com/openai/improved-diffusion), so if you can get your weights somehow loaded with codes in that repo, it should also work for ours.

**Comment by nityanandmathur** [comment]
Thank you for the information. I'll check it out.

Also, does your method supports unpaired image-to-image translation using LDMs?

**Comment by ChenWu98** [comment]
Yeah it does, though it's not reported in the paper. You may refer to ```config/experiments/translate_ffhq256_to_celeba256_latentdiff_ddim_eta01.cfg``` for details. I think simply setting ```RUN_NAME=translate_ffhq256_to_celeba256_latentdiff_ddim_eta01``` will probably work.

**Comment by nityanandmathur** [comment]
Thank you for the information. Could you please let me know which repository did you use to train the LDM?

**Comment by ChenWu98** [comment]
I used the pretrained models from https://github.com/CompVis/latent-diffusion.

**Comment by nityanandmathur** [comment]
Thank you for all the information!
