### ISSUE TITLE
main.py: error: the following arguments are required: --output_dir

### ISSUE THREAD

**Issue by LinjieFu-U** [ChenWu98/cycle-diffusion#3]
sorry,I do not know where can i set my parameter

**Comment by ChenWu98** [comment]
Hi, can you specify the command you are using so I can debug it?

**Comment by LinjieFu-U** [comment]
hi,I used the command you said in readme.md, and solved  the problem,but I find a new error.
FileNotFoundError: [Errno 2] No such file or directory: 'ckpts/ddpm/configs\\afhq.yml'

**Comment by ChenWu98** [comment]
This is because our path naming follows Linux instead of Windows. You can manually change ```ckpts/ddpm/configs``` to ```ckpts\ddpm\configs```, which also applies to other path errors on Windows.

**Comment by pseudo-usama** [comment]
@ChenWu98
Hi, I'm also getting this error (I'm Ubuntu user).
> FileNotFoundError: [Errno 2] No such file or directory: 'ckpts/ddpm/configs/afhq.yml'

Actually there was no such file when I cloned this repo. So what file do I supposed to create here?

**Comment by pseudo-usama** [comment]
I got it. I needed to download model files and config.zip. Mentioned in [README.md](https://github.com/ChenWu98/cycle-diffusion/blob/main/README.md)

> ```shell
> cd ckpts/
> mkdir ddpm
> cd ddpm/
> wget https://image-editing-test-12345.s3-us-west-2.amazonaws.com/checkpoints/celeba_hq.ckpt
> wget https://www.dropbox.com/s/g4h8sv07i3hj83d/ffhq_10m.pt
> wget https://www.dropbox.com/s/u74w8vaw1f8lc4k/afhq_dog_4m.pt
> wget https://www.dropbox.com/s/8i5aznjwdl3b5iq/cat_ema_0.9999_050000.pt
> wget https://www.dropbox.com/s/tplximipy8zxaub/wild_ema_0.9999_050000.pt
> wget https://www.dropbox.com/s/vqm6bxj0zslrjxv/configs.zip
> unzip configs.zip
> ```
