### ISSUE TITLE
install envionment issue

### ISSUE THREAD

**Issue by cuteboyqq** [ChenWu98/cycle-diffusion#30]
C:\Github_Code\GAN\cycle-diffusion>conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - pathlib2==2.3.6=py39h06a4308_2
  - cairo==1.16.0=hf32fb01_1
  - spyder-kernels==2.1.3=py39h06a4308_0
  - _ipyw_jlab_nb_ext_conf==0.1.0=py39h06a4308_0
  - yaml==0.2.5=h7b6447c_0
  - intel-openmp==2021.4.0=h06a4308_3561
  - locket==0.2.1=py39h06a4308_1
  - pywavelets==1.1.1=py39h6323ea4_4
  - openssl==1.1.1l=h7f8727e_0
  - conda-package-handling==1.7.3=py39h27cfd23_1
  - libev==4.33=h7f8727e_1
  - pluggy==0.13.1=py39h06a4308_0
  - ca-certificates==2021.10.26=h06a4308_2
  - importlib-metadata==4.8.1=py39h06a4308_0
  - libuv==1.40.0=h7b6447c_0
  - markupsafe==1.1.1=py39h27cfd23_0
  - statsmodels==0.12.2=py39h27cfd23_0
  - ld_impl_linux-64==2.35.1=h7274673_9
  - zope==1.0=py39h06a4308_1
  - xz==5.2.5=h7b6447c_0
  - pep8==1.7.1=py39h06a4308_0
  - mpfr==4.0.2=hb69a4c5_1
  - pyjwt==2.1.0=py39h06a4308_0
  - unixodbc==2.3.9=h7b6447c_0
  - fontconfig==2.13.1=h6c09931_0
  - widgetsnbextension==3.5.1=py39h06a4308_0
  - pytest==6.2.4=py39h06a4308_2
  - gstreamer==1.14.0=h28cd5cc_2
  - mistune==0.8.4=py39h27cfd23_1000
  - conda==4.10.3=py39h06a4308_0
  - scipy==1.7.1=py39h292c36d_2
  - sqlite==3.36.0=hc218d9a_0
  - navigator-updater==0.2.1=py39h06a4308_0
  - astroid==2.6.6=py39h06a4308_0
  - libstdcxx-ng==9.3.0=hd4cf53a_17
  - wurlitzer==2.1.1=py39h06a4308_0
  - pytables==3.6.1=py39h77479fe_1
  - py-lief==0.10.1=py39h2531618_1
  - libcurl==7.78.0=h0b77cf5_0
  - argon2-cffi==20.1.0=py39h27cfd23_1
  - cryptography==3.4.8=py39hd23ed53_0
  - typed-ast==1.4.3=py39h7f8727e_1
  - libxml2==2.9.12=h03d6c58_0
  - secretstorage==3.3.1=py39h06a4308_0
  - certifi==2021.10.8=py39h06a4308_0
  - zlib==1.2.11=h7b6447c_3
  - lerc==3.0=h295c915_0
  - chardet==4.0.0=py39h06a4308_1003
  - terminado==0.9.4=py39h06a4308_0
  - tbb4py==2021.4.0=py39hd09550d_0
  - setuptools==58.0.4=py39h06a4308_0
  - python==3.9.7=h12debd9_1
  - expat==2.4.1=h2531618_2
  - debugpy==1.4.1=py39h295c915_0
  - graphite2==1.3.14=h23475e2_0
  - kiwisolver==1.3.1=py39h2531618_0
  - boto==2.49.0=py39h06a4308_0
  - mpich==3.3.2=hc856adb_0
  - zfp==0.5.5=h2531618_6
  - krb5==1.19.2=hac12032_0
  - libtool==2.4.6=h7b6447c_1005
  - regex==2021.8.3=py39h7f8727e_0
  - jedi==0.18.0=py39h06a4308_1
  - sphinxcontrib==1.0=py39h06a4308_1
  - scikit-image==0.18.3=py39h51133e4_0
  - mkl_fft==1.3.1=py39hd3c417c_0
  - bzip2==1.0.8=h7b6447c_0
  - cycler==0.10.0=py39h06a4308_0
  - webencodings==0.5.1=py39h06a4308_1
  - arrow==0.13.1=py39h06a4308_0
  - ply==3.11=py39h06a4308_0
  - libarchive==3.4.2=h62408e4_0
  - bottleneck==1.3.2=py39hdd57654_1
  - mkl_random==1.2.2=py39h51133e4_0
  - msgpack-python==1.0.2=py39hff7bd54_1
  - wrapt==1.12.1=py39he8ac12f_1
  - giflib==5.2.1=h7b6447c_0
  - pyqt==5.9.2=py39h2531618_6
  - libpng==1.6.37=hbc83047_0
  - pyyaml==6.0=py39h7f8727e_1
  - zstd==1.4.9=haebb681_0
  - cffi==1.14.6=py39h400218f_0
  - libgfortran-ng==7.5.0=ha8ba4b0_17
  - pandas==1.3.4=py39h8c16a72_0
  - pyzmq==22.2.1=py39h295c915_1
  - charls==2.2.0=h2531618_0
  - libaec==1.0.4=he6710b0_1
  - pandocfilters==1.4.3=py39h06a4308_1
  - brotli==1.0.9=he6710b0_2
  - xlwt==1.3.0=py39h06a4308_0
  - zeromq==4.3.4=h2531618_0
  - anyio==2.2.0=py39h06a4308_1
  - libwebp==1.2.0=h89dd481_0
  - docutils==0.17.1=py39h06a4308_1
  - jxrlib==1.1=h7b6447c_2
  - libnghttp2==1.41.0=hf8bcb03_2
  - daal4py==2021.3.0=py39hae6d005_0
  - mypy_extensions==0.4.3=py39h06a4308_0
  - greenlet==1.1.1=py39h295c915_0
  - sniffio==1.2.0=py39h06a4308_1
  - matplotlib==3.4.3=py39h06a4308_0
  - pylint==2.9.6=py39h06a4308_1
  - ujson==4.0.2=py39h2531618_0
  - pyrsistent==0.18.0=py39heee7806_0
  - clyent==1.2.2=py39h06a4308_1
  - libssh2==1.9.0=h1ba5d50_1
  - tbb==2021.4.0=hd09550d_0
  - openjpeg==2.4.0=h3ad879b_0
  - mpmath==1.2.1=py39h06a4308_0
  - tornado==6.1=py39h27cfd23_0
  - gmpy2==2.0.8=py39h8083e48_3
  - watchdog==2.1.3=py39h06a4308_0
  - patchelf==0.13=h295c915_0
  - pycosat==0.6.3=py39h27cfd23_0
  - keyring==23.1.0=py39h06a4308_0
  - ncurses==6.3=heee7806_1
  - dbus==1.13.18=hb2f20db_0
  - jupyter==1.0.0=py39h06a4308_7
  - readline==8.1=h27cfd23_0
  - pip==21.2.4=py39h06a4308_0
  - spyder==5.1.5=py39h06a4308_1
  - numpy-base==1.20.3=py39h74d4b33_0
  - icu==58.2=he6710b0_3
  - ipykernel==6.4.1=py39h06a4308_1
  - psutil==5.8.0=py39h27cfd23_1
  - jupyter_server==1.4.1=py39h06a4308_0
  - sip==4.19.13=py39h2531618_0
  - libzopfli==1.0.3=he6710b0_0
  - qt==5.9.7=h5867ecd_1
  - libgfortran4==7.5.0=ha8ba4b0_17
  - blosc==1.21.0=h8c45485_0
  - pyerfa==2.0.0=py39h27cfd23_0
  - matplotlib-base==3.4.3=py39hbbc1b5f_0
  - cfitsio==3.470=hf0d0db6_6
  - llvmlite==0.37.0=py39h295c915_1
  - libffi==3.3=he6710b0_2
  - fastcache==1.1.0=py39he8ac12f_0
  - bitarray==2.3.0=py39h7f8727e_1
  - snappy==1.1.8=he6710b0_0
  - freetype==2.10.4=h5ab3b9f_0
  - jbig==2.1=hdba287a_0
  - libxslt==1.1.34=hc22bd24_0
  - libtiff==4.2.0=h85742a9_0
  - libxcb==1.14=h7b6447c_0
  - multipledispatch==0.6.0=py39h06a4308_0
  - brotlipy==0.7.0=py39h27cfd23_1003
  - glib==2.69.1=h5202010_0
  - unicodecsv==0.14.1=py39h06a4308_0
  - brunsli==0.1=h2531618_0
  - ipython==7.29.0=py39hb070fc8_0
  - tk==8.6.11=h1ccaba5_0
  - nbconvert==6.1.0=py39h06a4308_0
  - pycurl==7.44.1=py39h8f2d780_1
  - future==0.18.2=py39h06a4308_1
  - mkl==2021.4.0=h06a4308_640
  - lcms2==2.12=h3be6417_0
  - h5py==3.3.0=py39h930cdd6_0
  - inflection==0.5.1=py39h06a4308_0
  - get_terminal_size==1.0.0=haa9412d_0
  - imagecodecs==2021.8.26=py39h4cda21f_0
  - zope.interface==5.4.0=py39h7f8727e_0
  - numpy==1.20.3=py39hf144106_0
  - ruamel_yaml==0.15.100=py39h27cfd23_0
  - numba==0.54.1=py39h51133e4_0
  - curl==7.78.0=h1ccaba5_0
  - lxml==4.6.3=py39h9120a33_0
  - libdeflate==1.8=h7f8727e_5
  - libedit==3.1.20210910=h7f8727e_0
  - anaconda-client==1.9.0=py39h06a4308_0
  - harfbuzz==2.8.1=h6f93f22_0
  - path==16.0.0=py39h06a4308_0
  - cython==0.29.24=py39hdbfa776_0
  - lz4-c==1.9.3=h295c915_1
  - sympy==1.9=py39h06a4308_0
  - bkcharts==0.2=py39h06a4308_0
  - argh==0.26.2=py39h06a4308_0
  - mpi==1.0=mpich
  - numexpr==2.7.3=py39h22e1b3c_1
  - hdf5==1.10.6=hb1b8bf9_0
  - pillow==8.4.0=py39h5aabda8_0
  - scikit-learn==0.24.2=py39ha9443f7_0
  - cytoolz==0.11.0=py39h27cfd23_0
  - mkl-service==2.4.0=py39h7f8727e_0
  - pysocks==1.7.1=py39h06a4308_0
  - libgcc-ng==9.3.0=h5101ec6_17
  - distributed==2021.10.0=py39h06a4308_0
  - et_xmlfile==1.1.0=py39h06a4308_0
  - gmp==6.2.1=h2531618_2
  - gst-plugins-base==1.14.0=h8213a91_2
  - liblief==0.10.1=h2531618_1
  - notebook==6.4.5=py39h06a4308_0
  - libsodium==1.0.18=h7b6447c_0
  - dal==2021.3.0=h06a4308_557
  - libspatialindex==1.9.3=h2531618_0
  - libuuid==1.0.3=h7f8727e_2
  - zope.event==4.5.0=py39h06a4308_0
  - sqlalchemy==1.4.22=py39h7f8727e_0
  - fribidi==1.0.10=h7b6447c_0
  - pixman==0.40.0=h7f8727e_1
  - mpc==1.1.0=h10f8cd9_1
  - astropy==4.3.1=py39h09021b7_0
  - mccabe==0.6.1=py39h06a4308_1
  - entrypoints==0.3=py39h06a4308_0
  - lazy-object-proxy==1.6.0=py39h27cfd23_0
  - pyodbc==4.0.31=py39h295c915_0
  - bokeh==2.4.1=py39h06a4308_0
  - conda-build==3.21.5=py39h06a4308_0
  - pcre==8.45=h295c915_0
  - libgomp==9.3.0=h5101ec6_17
  - libllvm11==11.1.0=h3826bc1_0
  - gevent==21.8.0=py39h7f8727e_1
  - simplegeneric==0.8.1=py39h06a4308_2
  - scikit-learn-intelex==2021.3.0=py39h06a4308_0
  - jupyter_core==4.8.1=py39h06a4308_0
  - jpeg==9d=h7f8727e_0
  - pkginfo==1.7.1=py39h06a4308_0
  - patsy==0.5.2=py39h06a4308_0
  - rtree==0.9.7=py39h06a4308_1
  - libwebp-base==1.2.0=h27cfd23_0
  - _openmp_mutex==4.5=1_gnu
  - pango==1.45.3=hd140c19_0
  - c-ares==1.17.1=h27cfd23_0
  - lzo==2.10=h7b6447c_2
C:\Github_Code\GAN\cycle-diffusion>

my anaconada version is conda 23.7.4
OS: window 11
GPU: RTX2070

**Comment by ChenWu98** [comment]
Hi! I haven't tested with Windows. Maybe you can manually install the packages based on the "module not found" errors?
