### ISSUE TITLE
error from "import datasets import transformers" in the main.py

### ISSUE THREAD

**Issue by jxzhangjhu** [ChenWu98/cycle-diffusion#5]
Hi ChenWu98,

can you take a look at the error about import dtasets and import transformers when directly running the main.py?

**Comment by ChenWu98** [comment]
Hi Jiaxin, 

Can you provide the error log? I didn't see the error here.

**Comment by jxzhangjhu** [comment]
Hi Chen,

I think you have already added these packages into environment.yml but I followed your guidance by running

conda env create -f environment.yml
conda activate generative_prompt
pip install git+https://github.com/openai/CLIP.git

it still shows like, for example,  " No module named 'blobfile'" . It's weird...

**Comment by ChenWu98** [comment]
That's weird... Did you run `conda activate generative_prompt` each time before running the experiment? If so, can you do a sanity check such as opening a python and directly importing `blobfile` etc?

**Comment by jxzhangjhu** [comment]
Yes, I have activated the env and found only these three libraries that I need to reinstall 

pip install transformers 
pip install datasets
pip install blobfile 

now it works without the other library missing... 

thanks,

**Comment by ChenWu98** [comment]
Great!
